spring.application.name=gamification
server.port=8081

# Kubernetes Config
spring.config.import=optional:kubernetes:
spring.cloud.kubernetes.config.enabled=true
spring.cloud.kubernetes.config.name=${spring.application.name}
spring.cloud.kubernetes.reload.enabled=true
spring.cloud.kubernetes.discovery.enabled=false

##working with default logback configuration for distributed tracing
logging.pattern.level=[${spring.application.name:-},%X{traceId:-},%X{spanId:-}]
management.tracing.export.zipkin.endpoint=http://${SPRING_CLOUD_ZIPKIN_HOST:localhost}:9411/api/v2/spans

spring.pulsar.admin.service-url=http://${SPRING_CLOUD_PULSAR_HOST:localhost}:8080
spring.pulsar.client.service-url=pulsar://${SPRING_CLOUD_PULSAR_HOST:localhost}:6650

#---
# Docker Compose profile
spring.config.activate.on-profile=docker

#---
# Kubernetes profile
spring.config.activate.on-profile=kubernetes
spring.pulsar.admin.service-url=http://${SPRING_CLOUD_PULSAR_HOST:pulsar}:8080
spring.pulsar.client.service-url=pulsar://${SPRING_CLOUD_PULSAR_HOST:pulsar}:6650
management.tracing.export.zipkin.endpoint=http://${SPRING_CLOUD_ZIPKIN_HOST:zipkin}:9411/api/v2/spans

