spring.application.name=gamification
server.port=8081
# Gives us access to the H2 database web console
spring.h2.console.enabled=true
# Creates the database in a file
spring.datasource.url=jdbc:h2:file:~/gamification;AUTO_SERVER=TRUE
# Creates or updates the schema if needed
spring.jpa.hibernate.ddl-auto=update
# For educational purposes we will show the SQL in console
# spring.jpa.show-sql=true

spring.config.import=optional:consul:
spring.cloud.consul.host=${SPRING_CLOUD_CONSUL_HOST:localhost}
spring.cloud.consul.port=8500
spring.cloud.consul.config.prefixes[0]=config
spring.cloud.consul.config.format=YAML
spring.cloud.consul.config.default-context=application
spring.cloud.consul.config.watch.enabled=true
spring.cloud.consul.config.watch.delay=3000

spring.cloud.compatibility-verifier.enabled=false

##to avoid the pulsar listener creating non-partitioned topic
pulsar.attempts.topic=attempts.topic
pulsar.attempts.partitions=4

spring.pulsar.template.observations-enabled=true
spring.pulsar.listener.observation-enabled=true

##working with default logback configuration for distributed tracing
logging.pattern.level=[${spring.application.name:-},%X{traceId:-},%X{spanId:-}]

##During the process of creating the pulsar lazy producer in appender, there should no logs in the pulsar client code to append logs which would lead to dead lock
##Disable logs for pulsar client as a temp solution
logging.level.org.apache.pulsar.client.impl=OFF
logging.level.org.apache.pulsar.client.admin.PulsarAdmin=DEBUG

logging.include-application-name=false
management.tracing.sampling.probability=1
management.tracing.export.zipkin.endpoint=http://${SPRING_CLOUD_ZIPKIN_HOST:localhost}:9411/api/v2/spans

spring.pulsar.admin.service-url=http://${SPRING_CLOUD_PULSAR_HOST:localhost}:8080
spring.pulsar.client.service-url=pulsar://${SPRING_CLOUD_PULSAR_HOST:localhost}:6650

#---
spring.config.activate.on-profile=docker

